extends: airbnb

parser: babel-eslint
parserOptions:
  ecmaVersion: 6
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true

plugins:
  - react

rules:
  comma-dangle: off
  no-use-before-define: off
  no-console: off
  react/jsx-filename-extension: off